version: "2"
services:
    haproxy:
      container_name: haproxy
      image: daocloud.io/haproxy:1.4
      restart: always
      ports:
      - "3307:3306"
      volumes:
      - /root/haproxy-cfg:/usr/local/etc/haproxy
    
    node1:
      container_name: node1
      image: daocloud.io/airywenter/galera-mysql
      restart: always
      command: --wsrep-cluster-name=local-test --wsrep-cluster-address=gcomm://
    
    node2:
      container_name: node2
      image: daocloud.io/airywenter/galera-mysql
      restart: always
      command: --wsrep-cluster-name=local-test --wsrep-cluster-address=gcomm://node1
    
    node3:
      container_name: node3
      image: daocloud.io/airywenter/galera-mysql
      restart: always
      command: --wsrep-cluster-name=local-test --wsrep-cluster-address=gcomm://node1
#    
networks:
  galera-mysql:
    driver: overlay
